[package]
name = "pyscryer"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[lib]
name = "pyscryer"
crate-type = ["cdylib"]

[dependencies]
scryer-prolog = "0.9.4"
pyo3 = "0.20.2"
send_wrapper = "0.6.0"
